"""create room_categories table

Revision ID: d886ea88ca11
Revises: 38ed71af3946
Create Date: 2026-09-25 15:01:53.938735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd886ea88ca11'
down_revision: Union[str, Sequence[str], None] = '38ed71af3946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('uq_room_categories_single_default', 'room_categories', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_room_categories_single_default', table_name='room_categories', postgresql_where=sa.text('is_default'))
    op.drop_table('room_categories')
    # ### end Alembic commands ###
